---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: agugoat-github-pat
spec:
  encryptedData:
    token: AgDYR55YmCOSZXpTg/Kc+XYVp3bDz6pCfmcFuQx6jUUpZxC7dZ4Idx9v3H0NzHkqAV3SeSCOsLRXJg6YkuzMtRNKfL8QVMKuOI9izeJ8w1n3M3bfi0fLSJoqmXg9fpsKk9rY1IhjKIbhtpuymn7DPoT0POA46aKu3HlxiZdKdoJOktW/C/+BHLifLycGUgySNB/p5/CMotVjx/LXqYPMbGKVfEK190s2E/lVaJHM+TXFIbJZ/7rz1FjKtuLrEjLiWNlmYWGZ7JUumRX+5JGCwCH5Yz80EajxuDU8FqJbIyA3lsZsqWEhgmFBibwDrabDrtCz/GtLMVDnSiAC0fsdH28SuQvVTNSyM5s73k8XCAo6tjmSYWK+qKMja1a8g3hDLnX9hTNN9YFjTdQjWF+rfLA4aNAI4utTeM4utiulAMD2ZDafT2l9zBXJLP+A+jC+xluLov8m8EYFKNYp/asJJpyc+peakj2A8rsH8hqx8o4zrhREpYUGsFeQjpf0feCe8/6OkopCBuTrlxD8t2rojdyP6WxKJGolX1ZhHat1tXRsOcAgbaSaStcRzpLAAp5AXPZsDnScQb7oNmv8jt5MBAk/6BSa0MJNJyiO4kQ9sb1k8Ssh2QCLT0HowwDo3mvTbsB29I0wryPVvtOiAz1bgcVwyZH0Fk67bd+dx+B4pUb4dNN3wU8tRIolZDeun0K6nWIXY374PQo42SlqirTyqlBOnGLidoDHNVZMoRr6G9kOaHq3BD2gOH2h
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: agugoat-github-pat
