---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgCSxLJiUwYbcdwnAGuyxYsb1xTwg4FVD5RToTiazuBgzKiyGsvC0A+8XBKS1AFcItDJU5edBsOhxp5YEIPrA3cnTFZricRFf5PKLeeQsmAbZ8MsrBqQgT5S2qzMutUE4nEGTUDU+s5zEDPZ3IZAVFJETyBy13lqluwr+e+/N/UfOc8jQcFNfdjqVHGn4yFMEPd0Dt8T6icBGc+101SWDtiQVpWcqDQKWRaqHK983+bDk8ns9s+9uVJJ+aKrtKsVXGu9JUnHFk+nV850uyS901mfe2JNp4rJQwi/P4IpQr9NkU246t7mYk4B0PsUQz3TWOwRTMP7fzLoGUzgGy/6vvGTr8FUIc0xEALdaejuxODBmHkZ6uZUkZKcYeoB+EafQDaJX9bQFdPCDQiSIMbNsQx4SptTOu5C0TGQfLid1kOi7SaQ6TweYe+OmV7txQtkA48sXbTJiuOkspCeENI+/4qBUxoVPVWbsXEiLTwyPFZ89acjZRTtSC6lRoD+QXZHrLKBr51/OzTZfJeRjNYiLnni8BqFpWmina+p2w7Xmt8VlztgY6uBD72JE0hqjK7LbE8E3ht+JNeJOcLN1cWP7yCaWfKg9/dIPNbFHJcEcyJrK2cP1bRCgudw50fCR/+osPAQ9chplvbDQO2kAvXWEQ1j/lY46lqPbCEgiTPX1cLM1rX9u9UqGos2R66bOwJoA9lO/q5tonUktQALJ9A5s36QL6nvaQRTOTdTja4znlt8pC0gjUq9Qcvub3sT67qY66AVM7DhiRhHX5f360aUG6h8LDqv+a4zmUHZSV/wmuArMS6gqz1D9gk75N2f9mgbILX7xVdTtLYg8tu+qqT4Qp5IYDXKQI7rcekXT1K/moCKuPHCIIruBXpglzlcd/Nb1LK3dgbdjpA1lWmKACjMZouBz+EUi5HsYShlaOvjr+NMgC1h4h2/eBsT+AWboJXtBjW0hv+6bMGwwk/2Zp2qs2qO/MRSnOFoJ+SzzoruLCzGMKKH95y0E9TRqfMpNizCSELQXt9MdnXlKTEVHd0/MeeDbGUfCM/Foqdh2JWMwnPnq8zz2/b4Vwop2CK2ePjdl2x2lxuHajnHsxDybyUKbmzMrf8c/Wn9OOuoi4euWin3Rjk8Z1Akxx6ag4q5TW2RhaIoOAQzVtNqiEApRXSPgAG/+gzJ0jWXt/dVWzOUNp+l5Q6tjURlEQVR+az3Ornfva7soZI10VrUy/IVDZXIQfkT05/Wtt+iF7Bq2zEdmvPOzuWRLsO3sXm5uAEvH8gpHX7me9qt68x/gj34W8eIx/hlQKQLHhhzGZddqrcKXJgxP1o+RsySMhD2CRJqKih4HExSjfECmvtPcodAUoFUHXjCilWS1tQO0W594QwI19r0eGU4JRjK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson
