apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: integration-runtime
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem