apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-bar-ir
spec:
  description: >
    Builds an App Connect Enterprise BAR file from source.
    Compatible with IntegrationRuntime pipelines.
  params:
    - name: bar-file-name
      description: The name of the output BAR file
      type: string
    - name: application-name
      description: The name of the application to package
      type: string
    - name: project-folders
      description: Comma-separated list of ACE project folders to include
      type: string
  workspaces:
    - name: source
      description: Workspace containing the ACE source
  steps:
    - name: build-bar
      image: cp.icr.io/cp/appc/ace-server:12.0.10.0-r2  # or a newer tag if applicable
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -euo pipefail

        echo "Switching to application folder: $(params.application-name)"
        cd $(params.application-name)

        IFS=',' read -ra PROJECTS <<< "$(params.project-folders)"
        for project in "${PROJECTS[@]}"; do
          echo "Preparing project: $project"
          mkdir -p "$project/overrides"
        done

        echo "Building BAR file..."
        ibmint package --bar-file $(params.bar-file-name) --input-path $(IFS=','; echo "${PROJECTS[*]}")

        echo "BAR file created:"
        ls -lh $(params.bar-file-name)